### ISSUE TITLE
FileNotFoundError occurs

### ISSUE THREAD

**Issue by vegeta03** [oussama1598/edx_downloader#2]
```
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    edx.download_course(course_url)
  File "/home/vegeta/Workspace/edx/src/modules/edx.py", line 82, in download_course
    download_helpers.save_html(
  File "/home/vegeta/Workspace/edx/src/helpers/download_helpers.py", line 14, in save_html
    with open(full_path, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vegeta/Workspace/edx/courses/How to Code: Systematic Program Design - Part 1/3_1b: How to Design Functions/4_a_simple_practice_example/5_examples_/_check-expects.html'
```

Please provide a solution to this issue.

Thank you.

**Comment by vegeta03** [comment]
Added this line to `edx.py`:
```
material_title = material_title.replace("/","_")
```
